=== IgnacioElicegui/incubated/corosect/I4Submodel/schema_I4Submodel.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "refI4AssetId": {
      "type": "string"
    },
    "refI4AASId": {
      "type": "string"
    },
    "semanticId": {
      "type": "object",
      "properties": {
        "keys": {
          "type": "array",
          "items": {}
        }
      },
      "required": [
        "keys"
      ]
    },
    "qualifiers": {
      "type": "array",
      "items": {}
    },
    "hasDataSpecification": {
      "type": "array",
      "items": {}
    },
    "identification": {
      "type": "object",
      "properties": {
        "idType": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "idType",
        "id"
      ]
    },
    "administration": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "revision": {
          "type": "string"
        }
      },
      "required": [
        "version",
        "revision"
      ]
    },
    "idShort": {
      "type": "string"
    },
    "category": {
      "type": "string"
    },
    "modelType": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "kind": {
      "type": "string"
    },
    "submodelElements": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "refSubmodelElement": {
              "type": "string"
            },
            "idShort": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "modelType": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                }
              },
              "required": [
                "name"
              ]
            }
          },
          "required": [
            "refSubmodelElement",
            "idShort",
            "category",
            "modelType"
          ]
        },
        {
          "type": "object",
          "properties": {
            "refSubmodelElement": {
              "type": "string"
            },
            "idShort": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "modelType": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                }
              },
              "required": [
                "name"
              ]
            }
          },
          "required": [
            "refSubmodelElement",
            "idShort",
            "category",
            "modelType"
          ]
        },
        {
          "type": "object",
          "properties": {
            "refSubmodelElement": {
              "type": "string"
            },
            "idShort": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "modelType": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                }
              },
              "required": [
                "name"
              ]
            }
          },
          "required": [
            "refSubmodelElement",
            "idShort",
            "category",
            "modelType"
          ]
        }
      ]
    },
    "descriptions": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "language": {
              "type": "string"
            },
            "text": {
              "type": "string"
            }
          },
          "required": [
            "language",
            "text"
          ]
        }
      ]
    }
  },
  "required": [
    "id",
    "type",
    "refI4AssetId",
    "refI4AASId",
    "semanticId",
    "qualifiers",
    "hasDataSpecification",
    "identification",
    "administration",
    "idShort",
    "category",
    "modelType",
    "kind",
    "submodelElements",
    "descriptions"
  ]
}

=== IgnacioElicegui/incubated/SMARTMANUFACTURING/corosect/DigitalTwinExample/I4Submodel/OpeartionalData.json
{
        "id": "urn:ngsi-v2:RAMI40:I4Submodel:OperationalData:AASMRobotVI",
        "type": "I4Submodel",
        "administration": {
            "version": "1.0",
            "revision": ""
        },
        "category": "CONSTANT",
        "descriptions": [
            {
                "language": "en",
                "text": "It contains all the data related to operations of MRobot and VI system"
            }
        ],
        "hasDataSpecification": [],
        "idShort": "OperationalData",
        "identification": {
            "idType": "IRI",
            "id": "urn:ngsi-v2:RAMI40:I4Submodel:OperationalData:AASMRobotVI"
        },
        "kind": "Instance",
        "modelType": {
            "name": "Submodel"
        },
        "qualifiers": [],
        "refI4AASId": "urn:ngsi-v2:RAMI40:I4AAS:MRobotVI:AASMRobotVI",
        "refI4AssetId": "urn:ngsi-v2:RAMI40:I4Asset:MRobotVI:AASMRobotVI",
        "semanticId": {
            "keys": []
        },
        "submodelElements": [
            {
                "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:OperationalData:VIResults :AASMRobotVI",
                "idShort": "VIResults ",
                "category": "PARAMETER",
                "modelType": {
                    "name": "Property"
                }
            }
        ]
    }

=== IgnacioElicegui/incubated/SMARTMANUFACTURING/corosect/I4Submodel/examples/NamePlate.json
{
    "id": "urn:ngsi-v2:RAMI40:I4Submodel:Nameplate:AASMRobotVI",
    "type": "I4Submodel",
    "administration": {
        "version": "1.0",
        "revision": ""
    },
    "category": "CONSTANT",
    "descriptions": [
        {
            "language": "en",
            "text": "Contains data relared to the physical ICrate"
        }
    ],
    "hasDataSpecification": [],
    "idShort": "Nameplate",
    "identification": {
        "idType": "IRI",
        "id": "urn:ngsi-v2:RAMI40:I4Submodel:Nameplate:AASMRobotVI"
    },
    "kind": "Instance",
    "modelType": {
        "name": "Submodel"
    },
    "qualifiers": [],
    "refI4AASId": "urn:ngsi-v2:RAMI40:I4AAS:MRobotVI:AASMRobotVI",
    "refI4AssetId": "urn:ngsi-v2:RAMI40:I4Asset:MRobotVI:AASMRobotVI",
    "semanticId": {
        "keys": []
    },
    "submodelElements": [
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:ManufacturerName:AASMRobotVI",
            "idShort": "ManufacturerName",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:ManufacturerProductDesignation:AASMRobotVI",
            "idShort": "ManufacturerProductDesignation",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:ManufacturerProductFamily:AASMRobotVI",
            "idShort": "ManufacturerProductFamily",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:YearOfConstruction:AASMRobotVI",
            "idShort": "YearOfConstruction",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:SerialNumber:AASMRobotVI",
            "idShort": "SerialNumber",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:ClassificationSystem:AASMRobotVI",
            "idShort": "ClassificationSystem",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:DateOfManufacture:AASMRobotVI",
            "idShort": "DateOfManufacture",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:ProductCountryOfOrigin:AASMRobotVI",
            "idShort": "ProductCountryOfOrigin",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:QrCode:AASMRobotVI",
            "idShort": "QrCode",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:ProductIdentifier:AASMRobotVI",
            "idShort": "ProductIdentifier",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:CountryCode:AASMRobotVI",
            "idShort": "CountryCode",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:Street:AASMRobotVI",
            "idShort": "Street",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:Zip:AASMRobotVI",
            "idShort": "Zip",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:CityTown:AASMRobotVI",
            "idShort": "CityTown",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:Nameplate:StateCounty:AASMRobotVI",
            "idShort": "StateCounty",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        }
    ]
}

=== IgnacioElicegui/incubated/SMARTMANUFACTURING/corosect/I4Submodel/examples/example.json
{
  "id": "urn:ngsi-ld:RAMI40:I4Submodel:PositionalData:IC001",
  "type": "I4Submodel",
  "refI4AssetId": "urn:ngsi-ld:RAMI40:I4Asset:iCrate:IC001",
  "refI4AASId":"urn:ngsi-ld:RAMI40:I4AAS:iCrate:IC001",
  "semanticId": {
    "keys": []
  },
  "qualifiers": [],
  "hasDataSpecification": [],
  "identification": {
    "idType": "IRI",
    "id": "urn:ngsi-ld:RAMI40:I4Submodel:PositionalData:IC001"
  },
  "administration": {
    "version": "1.0",
    "revision": ""
  },
  "idShort": "PositionalData",
  "category": "CONSTANT",
  "modelType": {
    "name": "Submodel"
  },
  "kind": "Instance",
  "submodelElements": [
    {
      "refSubmodelElement": "urn:ngsi-ld:RAMI40:I4SubmodelElementProperty:PositionalData:PreviousPosition:IC001",
      "idShort": "PreviousPosition",
      "category": "PARAMETER",
      "modelType": {
        "name": "Property"
      }
    },
    {
      "refSubmodelElement": "urn:ngsi-ld:RAMI40:I4SubmodelElementProperty:PositionalData:CurrentPosition:IC001",
      "idShort": "CurrentPosition",
      "category": "PARAMETER",
      "modelType": {
        "name": "Property"
      }
    },
    {
      "refSubmodelElement": "urn:ngsi-ld:RAMI40:I4SubmodelElementProperty:PositionalData:NextPlannedPosition:IC001",
      "idShort": "NextPlannedPosition",
      "category": "PARAMETER",
      "modelType": {
        "name": "Property"
      }
    }
  ],
  "descriptions": [
    {
      "language": "en",
      "text": "Submodel positional data. Contains data about the position of the crate"
    }
  ]
}

=== IgnacioElicegui/incubated/SMARTMANUFACTURING/corosect/DigitalTwinExample/I4Submodel/AssetConditionMonitoring.json
{
    "id": "urn:ngsi-v2:RAMI40:I4Submodel:AssetConditionMonitoring:AASMRobotVI",
    "type": "I4Submodel",
    "administration": {
        "version": "1.0",
        "revision": ""
    },
    "category": "CONSTANT",
    "descriptions": [
        {
            "language": "en",
            "text": "Submodel asset condition monitoring[contains properties related to the health of the crate]"
        }
    ],
    "hasDataSpecification": [],
    "idShort": "AssetConditionMonitoring",
    "identification": {
        "idType": "IRI",
        "id": "urn:ngsi-v2:RAMI40:I4Submodel:AssetConditionMonitoring:AASMRobotVI"
    },
    "kind": "Instance",
    "modelType": {
        "name": "Submodel"
    },
    "qualifiers": [],
    "refI4AASId": "urn:ngsi-v2:RAMI40:I4AAS:MRobotVI:AASMRobotVI",
    "refI4AssetId": "urn:ngsi-v2:RAMI40:I4Asset:MRobotVI:AASMRobotVI",
    "semanticId": {
        "keys": []
    },
    "submodelElements": [
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:AssetConditionMonitoring:MRobotStatus:AASMRobotVI",
            "idShort": "MRobotStatus",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:AssetConditionMonitoring:MRobotMovementStatus:AASMRobotVI",
            "idShort": "MRobotMovementStatus",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:AssetConditionMonitoring:MRobotObjectHeld:AASMRobotVI",
            "idShort": "MRobotObjectHeld",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:AssetConditionMonitoring:MRobotTaskStatus:AASMRobotVI",
            "idShort": "MRobotTaskStatus",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:AssetConditionMonitoring:MRobotTaskID:AASMRobotVI",
            "idShort": "MRobotTaskID",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:AssetConditionMonitoring:VIStatus:AASMRobotVI",
            "idShort": "VIStatus",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:AssetConditionMonitoring:VITaskStatus:AASMRobotVI",
            "idShort": "VITaskStatus",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:AssetConditionMonitoring:VITaskID:AASMRobotVI",
            "idShort": "VITaskID",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementProperty:AssetConditionMonitoring:CobotDRobotWorkspaceFree:AASMRobotVI",
            "idShort": "CobotDRobotWorkspaceFree",
            "category": "PARAMETER",
            "modelType": {
                "name": "Property"
            }
        }
    ]
}

=== IgnacioElicegui/incubated/SMARTMANUFACTURING/corosect/I4Submodel/examples/OperationalCapability.json
{
    "id": "urn:ngsi-v2:RAMI40:I4Submodel:OperationalCapability:AASMRobotVI",
    "type": "I4Submodel",
    "administration": {
        "version": "1.0",
        "revision": ""
    },
    "category": "CONSTANT",
    "descriptions": [
        {
            "language": "en",
            "text": "Submodel operational capability [contains various data related to the operation capability of sensor]"
        }
    ],
    "hasDataSpecification": [],
    "idShort": "OperationalCapability",
    "identification": {
        "idType": "IRI",
        "id": "urn:ngsi-v2:RAMI40:I4Submodel:OperationalCapability:AASMRobotVI"
    },
    "kind": "Instance",
    "modelType": {
        "name": "Submodel"
    },
    "qualifiers": [],
    "refI4AASId": "urn:ngsi-v2:RAMI40:I4AAS:MRobotVI:AASMRobotVI",
    "refI4AssetId": "urn:ngsi-v2:RAMI40:I4Asset:MRobotVI:AASMRobotVI",
    "semanticId": {
        "keys": []
    },
    "submodelElements": [
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementOperation:OperationalCapability:MRobotReturnStackError:AASMRobotVI",
            "idShort": "MRobotReturnStackError",
            "category": "PARAMETER",
            "modelType": {
                "name": "Operation"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementOperation:OperationalCapability:MRobotExecuteTask:AASMRobotVI",
            "idShort": "MRobotExecuteTask",
            "category": "PARAMETER",
            "modelType": {
                "name": "Operation"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementOperation:OperationalCapability:MRobotStop:AASMRobotVI",
            "idShort": "MRobotStop",
            "category": "PARAMETER",
            "modelType": {
                "name": "Operation"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementOperation:OperationalCapability:MRobotEmergencyStop:AASMRobotVI",
            "idShort": "MRobotEmergencyStop",
            "category": "PARAMETER",
            "modelType": {
                "name": "Operation"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementOperation:OperationalCapability:MRobotResume:AASMRobotVI",
            "idShort": "MRobotResume",
            "category": "PARAMETER",
            "modelType": {
                "name": "Operation"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementOperation:OperationalCapability:VIStop:AASMRobotVI",
            "idShort": "VIStop",
            "category": "PARAMETER",
            "modelType": {
                "name": "Operation"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementOperation:OperationalCapability:VIStart:AASMRobotVI",
            "idShort": "VIStart",
            "category": "PARAMETER",
            "modelType": {
                "name": "Operation"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementOperation:OperationalCapability:VIReturnStackError:AASMRobotVI",
            "idShort": "VIReturnStackError",
            "category": "PARAMETER",
            "modelType": {
                "name": "Operation"
            }
        },
        {
            "refI4SubmodelElement": "urn:ngsi-v2:RAMI40:I4SubmodelElementOperation:OperationalCapability:VIHistData:AASMRobotVI",
            "idShort": "VIHistData",
            "category": "PARAMETER",
            "modelType": {
                "name": "Operation"
            }
        }
    ]
}
