=== IgnacioElicegui/incubated/SMARTENERGY/BatteriePass/original/CarbonFootprint-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "components": {
    "schemas": {
      "urn_samm_BatteryPass_1.0.0_BatteryCarbonFootprint": {
        "type": "number",
        "description": "The battery carbon footprint is an aggregation of the carbon footprint of the individual lifecycle stages"
      },
      "urn_samm_BatteryPass_1.0.0_LifeCycleStage": {
        "type": "string",
        "enum": [
          "RawMaterialExtraction",
          "MainProduction",
          "Distribution",
          "Recycling"
        ]
      },
      "urn_samm_BatteryPass_1.0.0_CarbonFootprintPerLifecycleStage": {
        "type": "number"
      },
      "urn_samm_BatteryPass_1.0.0_CarbonFootprintperLifecycleStage": {
        "description": "The carbon footprint of the battery as share of total Battery Carbon Footprint, differentiated per life cycle stage",
        "type": "object",
        "properties": {
          "lifeCycleStage": {
            "description": "The description of the life cycle stage ",
            "$ref": "#/components/schemas/urn_samm_BatteryPass_1.0.0_LifeCycleStage"
          },
          "carbonFootprintPerLifecycleStage": {
            "description": "Carbon footprint of the individual lifecycle stage",
            "$ref": "#/components/schemas/urn_samm_BatteryPass_1.0.0_CarbonFootprintPerLifecycleStage"
          }
        },
        "required": [
          "lifeCycleStage",
          "carbonFootprintPerLifecycleStage"
        ]
      },
      "urn_samm_BatteryPass_1.0.0_CarbonFootprints": {
        "description": "CarbainFootprints per lifecycle stage",
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/urn_samm_BatteryPass_1.0.0_CarbonFootprintperLifecycleStage"
        },
        "uniqueItems": true
      },
      "urn_samm_BatteryPass_1.0.0_CarbonFootprintPerformanceClass": {
        "type": "string",
        "description": "EV, industrial and LMT batteries shall bear a conspicuous, clearly legible and indelible label indicating the carbon footprint of the battery and the carbon footprint performance class that the relevant battery model per manufacturing plant corresponds to. The carbon footprint performance class shall be accessible via the battery passport. A meaningful number of classes of performance will be developed (ï¿½) with category A being the best class with the lowest carbon footprint life cycle impact."
      },
      "urn_samm_org.eclipse.esmf.samm_characteristic_2.0.0_ResourcePath": {
        "type": "string",
        "format": "uri",
        "description": "The path of a resource."
      }
    }
  },
  "properties": {
    "batteryCarbonFootprint": {
      "description": "The carbon footprint of the battery, calculated as kg of carbon dioxide equivalent per one kWh of the total energy provided by the battery over its expected service life, as declared in the Carbon Footprint Declaration.",
      "$ref": "#/components/schemas/urn_samm_BatteryPass_1.0.0_BatteryCarbonFootprint"
    },
    "carbonFootprintperLifecycleStage": {
      "description": "The carbon footprint of the battery as share of total Battery Carbon Footprint, differentiated per life cycle stages raw material extraction, battery production, distribution and recycling.",
      "$ref": "#/components/schemas/urn_samm_BatteryPass_1.0.0_CarbonFootprints"
    },
    "carbonFootPrintPerformanceClass": {
      "description": "The carbon footprint performance class that the relevant battery model per manufacturing plant corresponds to.",
      "$ref": "#/components/schemas/urn_samm_BatteryPass_1.0.0_CarbonFootprintPerformanceClass"
    },
    "carbonFoortPrintStudy": {
      "description": "A web link to get access to a public version of the study supporting the carbon footprint values.",
      "$ref": "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.0.0_ResourcePath"
    }
  },
  "required": [
    "batteryCarbonFootprint",
    "carbonFootprintperLifecycleStage",
    "carbonFootPrintPerformanceClass",
    "carbonFoortPrintStudy"
  ]
}

=== IgnacioElicegui/incubated/SMARTENERGY/BatteriePass/original/CarbonFootprint-sample.json
{
  "carbonFootprintperLifecycleStage": [
    {
      "lifeCycleStage": "RawMaterialExtraction",
      "carbonFootprintPerLifecycleStage": 0
    }
  ],
  "carbonFoortPrintStudy": "telnet://192.0.2.16:80/",
  "batteryCarbonFootprint": 0,
  "carbonFootPrintPerformanceClass": "eOMtThyhVNLWUZNRcBaQKxI"
}
